# Generated by Django 5.1.4 on 2025-01-09 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('itemID', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=200)),
                ('item_category', models.CharField(choices=[('medication', 'medication'), ('lab supplies', 'lab supplies'), ('others', 'others')], max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reorder_level', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('medicationID', models.AutoField(primary_key=True, serialize=False)),
                ('medication_name', models.CharField(max_length=200)),
                ('medication_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('serviceID', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=200)),
                ('service_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
