# Generated by Django 5.1.4 on 2025-01-09 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('labresultID', models.AutoField(primary_key=True, serialize=False)),
                ('lab_number', models.CharField(max_length=50)),
                ('date_of_test', models.DateTimeField()),
                ('test_name', models.CharField(max_length=200)),
                ('test_result', models.TextField()),
                ('reference_range', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('medicalhistoryID', models.AutoField(primary_key=True, serialize=False)),
                ('history_notes', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaintID', models.AutoField(primary_key=True, serialize=False)),
                ('complaint_date', models.DateTimeField()),
                ('complaint_description', models.TextField()),
                ('medical_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.medicalhistory')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescriptionID', models.AutoField(primary_key=True, serialize=False)),
                ('prescription_date', models.DateTimeField()),
                ('medicine_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('treatmentID', models.AutoField(primary_key=True, serialize=False)),
                ('treatment_date', models.DateTimeField()),
                ('treatment_description', models.TextField()),
                ('medical_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.medicalhistory')),
            ],
        ),
    ]
